name: Dynamic Code Analysis Valgrind
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install dependency
      run: |
        sudo apt-get -y install valgrind
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
    - name: make test
      run: make -C Implementation/ test
    - name: make valgrind
      run: valgrind ./Implementation/Build/Test_MINIPROJECT-STEPIN-298287.out
        
